name: 'github-package-version'
description: 'Get the latest version of a package from GitHub Packages'
author: 'Svetlin Ralchev'

# Define your inputs here.
inputs:
  github-token:
    description: 'The GitHub token used to create an authenticated client'
    default: '${{ github.token }}'
    required: true
  github-package-type:
    description: 'The GitHub package type'
    default: 'npm'
    required: true

runs:
  using: node20
  main: dist/index.js
